export { Home } from './home/Home';
export { About } from './about/About';
export { Curriculums } from './curriculum/Curriculums';
export { Admission } from './admission/Admission';
export { Facility } from './facilities/Facility';
export { Program } from './program/Program';
export { AnnouncementsPage } from './announcements/Announcements';
export { ContactUs } from './contactUs/ContactUs';
export { Prospectus } from './prospectus/Prospectus';
export { Faculty } from './faculty/Faculty';
export { GalleryPage } from './gallery/GalleryPage';
export { Blog } from './blog/Blog';
export { BlogPost } from './blog/BlogPost';
export { default as NotFound } from './NotFound';
